name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: checkout
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install Packages
        run: npm install
      - name: env
        env:
          MAPBOX: ${{secrets.REACT_APP_MAPBOX}}
        shell: bash
        run: |
            echo "REACT_APP_MAPBOX=$MAPBOX" > .env
      - name: Build page
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
